name: Update jpf-core Wiki
on: [push]
jobs:
  Push-Update:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          WIKI_SECRET: ${{ secrets.UPDATEWIKISECRETS }}
        run: |
          git clone https://$WIKI_SECRET@github.com/quadhier/from
          cd from
          git config user.name "quadhier"
          git config user.email "quadhier@163.com"
          git remote add upstream https://$WIKI_SECRET@github.com/quadhier/to
          git fetch origin
          git fetch upstream
          git merge upstream/main --no-edit
          git push origin HEAD:main
          git push upstream HEAD:main
